learning_templates/basic_app/urls.py
from django.conf.urls import url
from basic_app import views

app_name='basic_app'
urlpatterns=[
    url(r'^relative/',views.relative,name='relative'),
    url(r'^other/',views.other,name='other'),
]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path
from basic_app import views
from django.conf.urls import url,include

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^basic_app/',include('basic_app.urls')),
]

learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

learning_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict={'text':'hello world','number':100}
    return render(request,"basic_app/index.html",context_dict)


def other(request):
    return render(request,"basic_app/other.html")

def relative(request):
    return render(request,"basic_app/relative_url_templates.html")

learning_templates/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>
      <nav class='navbar navbar-default navbar-static-top'>
        <div class="container">
          <ul class='nav navbar-nav'>
            <li ><a class='navbar-brand' href="{% url 'index' %}">BRAND</a></li>
            <li><a class='navbar-link' href="{% url 'admin:index' %}">ADMIN</a></li>
            <li><a class='navbar-link' href="{% url 'basic_app:other' %}">OTHER</a></li>
          </ul>
        </div>
      </nav>
      <div class="container">
        {%  block body_block %}
        {% endblock %}
      </div>
  </body>
</html>

learning_templates/templates/basic_app/index.html
<!doctype html>

{% extends "basic_app/base.html" %}

  {% block body_block %}
  {% load my_extra %}
    <h1>Welcome to INDEX</h1>
    <h2>This is index.html showing</h2>
    <h1>{{ text|decoy:'world'  }}</h1>
    <h1>{{ number|add:"99" }}</h1>
    {% endblock %}

learning_templates/templates/basic_app/other.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
  {% block body_block %}
    <h1>WELCOME TO OTHER</h1>
    <h2>This isw an example of Inheritance</h2>
    {% endblock %}

learning_templates/templates/basic_app/relative_url_templates.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Welcome to RELATIVE URL TEMPLATES</h1>
    <a href="{% url 'basic_app:other' %}">THE OTHER PAGE</a>
    <a href="{% url 'admin:index' %}">Link to admin</a>
    <a href="{% url 'index' %}">INDEX</a>
  </body>
</html>